[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.20.8"

# Skip problematic pages during build
[[redirects]]
  from = "/admin/*"
  to = "/auth/login"
  status = 302

[[redirects]]
  from = "/doctor/*"
  to = "/auth/login"
  status = 302

[[redirects]]
  from = "/lab/*"
  to = "/auth/login"
  status = 302

[[redirects]]
  from = "/patient/*"
  to = "/auth/login"
  status = 302

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
